### ISSUE TITLE
MYSQL链接不上

### ISSUE THREAD

**Issue by juvin-git** [idoop/zentao#11]
mysql报10061 unknow error !
使用 adminer客户端，也报错
`
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at zentao@localhost.net to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
`

**Comment by idoop** [comment]
@CreatNameHard 能看一下你的`docker-compose.yaml`的配置吗?

**Comment by juvin-git** [comment]
> 
> 
> @CreatNameHard 能看一下你的`docker-compose.yaml`的配置吗?

```
version: '3'
networks:
  dev-net:
    driver: bridge
services:
 zentao:
    image: idoop/zentao:11.3
    container_name: zentao
    restart: always
    ports:
      - 50080:80
      - 53306:3306
    volumes:
    - /data/zbox/:/opt/zbox/
    environment:
      - USER="admin"
      - PASSWD="admin123"
      - BIND_ADDRESS="false"
    networks:
     - dev-net
```
