### ISSUE TITLE
服务启动成功但是不能登录

### ISSUE THREAD

**Issue by pangff** [idoop/zentao#24]
配置并启动成功了，
但是admin 123456 登录会回到登录页 
zentao/cron-ajaxExec-0.html canceled

使用 root/password 也不行

**Comment by idoop** [comment]
应该不会，你试试老版本的。

**Comment by pangff** [comment]
@idoop  11.6.5 版本可以吗。我刚用的是latest

**Comment by pangff** [comment]
替换了11.6.5还是不行

docker run -d -p 8081:80 -p 3306:3306 \
        -e ADMINER_USER="root" -e ADMINER_PASSWD="password" \
        -e BIND_ADDRESS="false" \
        -v /mnt/zentao/data/:/opt/zbox/ \
        --add-host smtp.exmail.qq.com:163.177.90.125 \
        --name zentao-server \
        idoop/zentao:11.6.5

<img width="838" alt="截屏2019-11-28下午2 49 30" src="https://user-images.githubusercontent.com/2368696/69783371-5d188c80-11ee-11ea-8f1a-a62fef572ed2.png">

**Comment by idoop** [comment]
那可能就是你本地环境或配置的问题了。

**Comment by pangff** [comment]
本地没有特别配置，端口是8081到80  下面是nginx 配置
```

server {	
   listen 80;
   server_name zd.xxx.com;
   rewrite ^(.*)$ https://${server_name}$1 permanent; 
}


 server {
    listen 443 ssl; # managed by Certbot
    server_name zd.xxx.com;
    ssl_certificate /etc/letsencrypt/live/zd.xxx.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/zd.xxx.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

     location / {
        client_body_buffer_size      500M;
        client_max_body_size 200M;
        proxy_redirect     off;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8081/;
   }

}
```

**Comment by idoop** [comment]
建议先直接访问，因为容器中自带Apache。确认没问题了，再放Nginx反向代理。

**Comment by pangff** [comment]
直接访问可以，nginx代理就不行，这是什么原因呢

**Comment by idoop** [comment]
那只能是你的Nginx配置文件的问题，试试先把`proxy_set_header`字段去掉。

**Comment by pangff** [comment]
好像是时区问题（zentao容器和宿主机时区不一致），造成了cookie失效。目前zentao容器可以进行时区配置吗？我试了不行

```
$tzselect
/usr/bin/tzselect: line 180: /usr/share/zoneinfo/iso3166.tab: No such file or directory
/usr/bin/tzselect: time zone files are not set up correctly
```

**Comment by idoop** [comment]
时区问题是比较简单的，容器默认为UTC时区，只需把宿主机的本地时区挂载到容器中即可。
```yaml
...
    volumes:
    - /etc/localtime:/etc/localtime:ro
..
```

**Comment by idoop** [comment]
我关了这个issue，如果还有问题，请重开。

**Comment by pangff** [comment]
修改了时区问题，还是没有解决。和时区无关 @idoop   请测试nginx方向代理对情况，目前看应该是有问题的

**Comment by idoop** [comment]
老弟，这明显是你的上层Nginx转发的配置问题，上百度或者谷歌搜下吧。

**Comment by pangff** [comment]
> 老弟，这明显是你的上层Nginx转发的配置问题，上百度或者谷歌搜下吧。

@idoop 
nginx转发做了很多次的修改了，而且在 issue #18 也有人遇到。目前nginx的配置已经贴出来了。我相信只要使用nginx做反向代理的用户必然会遇到相同问题。

```
server {	
   listen 80;
   server_name zd.xxx.com;
   rewrite ^(.*)$ https://${server_name}$1 permanent; 
}


 server {
    listen 443 ssl; # managed by Certbot
    server_name zd.xxx.com;
    ssl_certificate /etc/letsencrypt/live/zd.xxx.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/zd.xxx.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

     location / {
        client_body_buffer_size      500M;
        client_max_body_size 200M;
        proxy_redirect     off;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:8081/;
   }

}
```

**Comment by xiaopohair** [comment]
单独这么转发确实是不行，后来我是直接在容器的apache里做了vhost配置，然后就可以了。
但现在也有问题，不稳定，不定时的重启。
```Listen 443
<VirtualHost *:80>
  ServerName pms.**.**
  RewriteEngine on
  RewriteCond %{SERVER_PORT} !^443$
  RewriteRule ^/?(.*)$ https://%{SERVER_NAME}/$1 [L,R]
</VirtualHost>

<VirtualHost *:443>
  ServerName pms.**.**
  DocumentRoot "/opt/zbox/app/zentao/www"

  SSLEngine on
  SSLProtocol all -SSLv2 -SSLv3
  SSLCipherSuite HIGH:!RC4:!MD5:!aNULL:!eNULL:!NULL:!DH:!EDH:!EXP:+MEDIUM
  SSLHonorCipherOrder on

  SSLCertificateFile /opt/zbox/ssl/fullchain.pem
  SSLCertificateKeyFile /opt/zbox/ssl/privkey.pem
  SSLCertificateChainFile /opt/zbox/ssl/chain.pem

  <Directory />
    AllowOverride all
    Require all granted
  </Directory>
  ErrorLog "/opt/zbox/logs/apache_error_log"
  CustomLog "/opt/zbox/logs/apache_access_log" combind
</VirtualHost>```

**Comment by pangff** [comment]
还有什么办法吗，重启原因是什么呢。
@xiaopohair @idoop

**Comment by xiaopohair** [comment]
我问了禅道。说是一键安装包部署在docker下面之后，性能有损耗，让我还是部署在实体机下面。不知道是不是应该调整一下docker配置，给这个容器多分配点资源。

**Comment by idoop** [comment]
@xiaopohair 打包成容器是为了方便部署，性能倒是其次的，毕竟能选择用禅道的公司的员工数量不会上万，也不会每秒请求禅道上千次。
你俩是铁了心要放个前置代理还用上SSL，那我一会试下，然后给你们贴下Nginx的配置。

**Comment by idoop** [comment]
@xiaopohair @pangff 
以下配置我测试是OK的，你们可以参考下。

docker-compose.yaml
```yaml
version: "2.2"
services:
  zentao:
    image: idoop/zentao:latest
    container_name: zentao
    environment:
    # specifies Adminer account and password for web login database.
      USER: "root"
      PASSWD: "123456"
      BIND_ADDRESS: "false"
    extra_hosts:
      - "smtp.exmail.qq.com:163.177.90.125"
    volumes:
      - ./data:/opt/zbox/
    restart: always
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - zentao
    restart: always
    logging:
      options:
        max-size: "2m"
        max-file: "5"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # certificate
      - ./cert:/etc/nginx/ssl:ro
      # config
      - ./ng_zentao.conf:/etc/nginx/conf.d/default.conf:ro
```

Nginx for zentao config
```nginx
server {
  listen 80;
  listen [::]:80;
#  server_name localhost;
  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2 fastopen=3 reuseport;
  listen [::]:443 ssl http2;
#  listen [::]:443 default ipv6only=on;
#  server_name localhost;
  client_max_body_size 100m;
  client_body_buffer_size 1m;
  access_log off;

#  root /var/www/html;
#  index index.php index.html index.htm;

  server_tokens off;

  #open HSTS
  add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;
  #hijack
  add_header X-Frame-Options "SAMEORIGIN" always;
  #XSS attack
  add_header X-XSS-Protection "1; mode=block" always;
  #MIME survey 
  add_header X-Content-Type-Options "nosniff" always;

  #replace your certcifcate files.
  ssl_certificate /etc/nginx/ssl/fullchain.cer;
  ssl_certificate_key /etc/nginx/ssl/domain.key;

  ssl_prefer_server_ciphers on;
  ssl_session_cache builtin:1000 shared:SSL:20m;
  ssl_session_timeout 180m;
  ssl_stapling on;
  ssl_stapling_verify on;


  http2_push_preload on;
  add_header Set-Cookie "session=1";

  location / {
    proxy_redirect off;
    proxy_pass http://zentao:80;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
  }

  location ~* \.(jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|ttf|ttc|otf|eot|woff)$ {
    try_files $uri /index.php?$query_string;
    add_header Access-Control-Allow-Origin *;
    #expires max;
    #access_log off;
    #log_not_found off;
  }

  location = /favicon.ico {
    log_not_found off;
    access_log off;
  }
}
```
如果没有其他问题的话，请 @pangff Close #26 。
